In [10]:
import sys
import os

current_file_path = os.path.abspath(os.getcwd()) # Funciona solo para JupyterNotebooks

# Obtener la ruta del directorio raíz del proyecto
project_root = os.path.abspath(os.path.join(os.path.dirname(current_file_path)))

# Añadir el directorio raíz del proyecto al sys.path
sys.path.append(project_root)

from config import INPUTS_FOLDER

statement_path = os.path.join(INPUTS_FOLDER, 'test_files', 'Banorte', 'Banorte_credit_new_statement.pdf')
statement_path

'c:\\Proyectos\\Aether\\Aether_v1\\documents\\inputs\\test_files\\Banorte\\Banorte_credit_new_statement.pdf'

In [11]:
from document_reader import PDFReader
from bank_detector import DefaultBankDetector

bank_detector = DefaultBankDetector(PDFReader(statement_path))

extracted_words = bank_detector.extracted_words
extracted_words

,page,text,x0,top,x1,bottom
0,2,2,553.038000,52.095053,557.486139,60.095303
1,2,de,559.703069,52.095053,568.599347,60.095303
2,2,8,570.831000,52.095053,575.279139,60.095303
3,2,MARIA,45.021750,72.287250,73.497750,81.287250
4,2,FERNANDA,75.990750,72.287250,125.454750,81.287250
...,...,...,...,...,...,...
4218,8,opinión,131.473888,754.353053,171.118789,765.353303
4219,8,de,174.165858,754.353053,186.992150,765.353303
4220,8,este,190.039219,754.353053,212.050719,765.353303
4221,8,comparativo:,215.097788,754.353053,284.124357,765.353303
4222,8,https://www.banxico.org.mx/opinioncuadro,287.382750,754.353053,512.833218,765.353303

In [12]:
bank = bank_detector.detect_bank()
statement_type = bank_detector.detect_statement_type()
statement_properties = bank_detector.get_statement_properties()

print(f'{bank} - {statement_type}')

banorte - credit

In [13]:
from table_boundary_detector import TransactionTableBoundaryDetector

boundary_detector = TransactionTableBoundaryDetector(extracted_words, statement_properties)

start_idx = boundary_detector.start_idx
end_idx = boundary_detector.end_idx

if statement_type == 'credit' and start_idx is None or end_idx is None:
    print('New format')
    statement_properties = bank_detector.get_statement_properties(new_credit_format= True)
    boundary_detector = TransactionTableBoundaryDetector(extracted_words, statement_properties)
    
    start_idx = boundary_detector.start_idx
    end_idx = boundary_detector.end_idx

df_table = boundary_detector.get_filtered_table_words()

print(f'{start_idx} - {end_idx}')
df_table

New format
1035 - 1279

     page      text         x0        top         x1     bottom
0       4       (NO  375.81825  142.42575  392.30625  151.42575
1       4         A  394.79925  142.42575  401.29725  151.42575
2       4    MESES)  403.79025  142.42575  438.26025  151.42575
3       4   Tarjeta  224.30850  152.56125  253.13550  161.56125
4       4   titular  255.62850  152.56125  280.60350  161.56125
..    ...       ...        ...        ...        ...        ...
239     4  09/11/24  138.66450  580.09725  173.00850  589.09725
240     4   85.8515  175.50150  580.09725  208.01850  589.09725
241     4       USD  210.51150  580.09725  229.50150  589.09725
242     4        RT  231.99450  580.09725  243.82050  589.09725
243     4   19.9381  246.31350  580.09725  278.83050  589.09725

[244 rows x 6 columns]

In [14]:
from row_segmenter import TransactionRowSegmenter

row_segmenter = TransactionRowSegmenter(df_table, statement_properties)

column_delimitation = row_segmenter.delimit_column_positions()
grouped_rows = row_segmenter.group_rows()

print(row_segmenter.row_threshold)
print(column_delimitation)
grouped_rows

0.9954999999999989
{'columns': ['Fecha de la operación', 'Fecha de cargo', 'Descripción del movimiento', 'Monto'], 'x0': [36.816, 92.16825, 279.63525, 542.154], 'x1': [75.2703615, 118.84887524999999, 377.4143055, 564.3786944999999]}

,row_group,text,words,top,bottom,page
0,0,(NO A MESES),"[((NO, 375.8182499999999, 392.3062499999999), ...",142.425750,151.425750,4
1,1,Tarjeta titular XXXX XXXX XXXX 4540,"[(Tarjeta, 224.30849999999998, 253.13549999999...",152.561250,161.561250,4
2,2,Fecha de Fecha de,"[(Fecha, 36.816, 59.0406945), (de, 61.25676375...",165.994553,173.994802,4
3,3,Monto,"[(Monto, 542.154, 564.3786944999999)]",168.999053,176.999302,4
4,4,Descripción del movimiento,"[(Descripción, 279.63525, 321.42055575), (del,...",170.499053,178.499302,4
5,5,la operación cargo,"[(la, 31.701, 37.925194499999996), (operación,...",175.003553,183.003803,4
6,6,D LOCAL*DIDIFOOD CIUDAD DE MEX MX DMM 171208LT...,"[(D, 138.6645, 145.1625), (LOCAL*DIDIFOOD, 147...",188.781750,197.781750,4
7,7,AMAZON MX A MESES M CIUDAD DE M 02/03 12-SEP-2...,"[(AMAZON, 138.6645, 177.13049999999998), (MX, ...",205.059000,214.059000,4
8,8,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4 ...,"[(DLOCAL*DIDI, 138.6645, 196.13850000000002), ...",221.337000,230.337000,4
9,9,SIMILARES F3 OTE MERIDA YUC MX CCA 010830V77 1...,"[(SIMILARES, 138.6645, 186.62550000000002), (F...",237.615000,246.615000,4
10,10,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4 ...,"[(DLOCAL*DIDI, 138.6645, 196.13850000000002), ...",253.893000,262.893000,4
11,11,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4 ...,"[(DLOCAL*DIDI, 138.6645, 196.13850000000002), ...",270.171000,279.171000,4
12,12,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4 ...,"[(DLOCAL*DIDI, 138.6645, 196.13850000000002), ...",286.448250,295.448250,4
13,13,"PAGO BANCA DIGITAL / SUCURSAL, GRACIAS. 21-SEP...","[(PAGO, 138.6645, 163.9725), (BANCA, 166.4655,...",302.726250,311.726250,4
14,14,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4 ...,"[(DLOCAL*DIDI, 138.6645, 196.13850000000002), ...",319.004250,328.004250,4
15,15,APPLE.COM/BILL 866-712-77 25-SEP-2024 26-SEP-2...,"[(APPLE.COM/BILL, 138.6645, 212.1135), (866-71...",335.282250,344.282250,4
16,16,09/25/24 2.5017 USD RT 19.6866,"[(09/25/24, 138.6645, 173.6745), (2.5017, 176....",347.979750,356.979750,4
17,17,DLOCAL*DIDI FOODS MIGUEL HIDALG MX DME 180122D...,"[(DLOCAL*DIDI, 138.6645, 196.13850000000002), ...",364.610250,373.610250,4
18,18,DLOCAL*DIDI FOODS MIGUEL HIDALG MX DME 180122D...,"[(DLOCAL*DIDI, 138.6645, 196.13850000000002), ...",380.887500,389.887500,4
19,19,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4 ...,"[(DLOCAL*DIDI, 138.6645, 196.13850000000002), ...",397.165500,406.165500,4
20,20,COMISION ADMINISTRACION TARJETA TITULAR 30-SEP...,"[(COMISION, 138.6645, 184.12349999999998), (AD...",413.443500,422.443500,4
21,21,16.00 % IVA SOBRE COMISIONES E INTERESES 30-SE...,"[(16.00, 138.6645, 161.1735), (%, 163.6665, 17...",429.721500,438.721500,4
22,22,AMAZON MX MARKETPLACE CIUDAD DE MEX MX ANE 140...,"[(AMAZON, 138.6645, 177.13049999999998), (MX, ...",445.999500,454.999500,4
23,23,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4 ...,"[(DLOCAL*DIDI, 138.6645, 196.13850000000002), ...",462.276750,471.276750,4
24,24,D LOCAL*DIDI RIDES CIUDAD DE MEX MX DMM 171208...,"[(D, 138.6645, 145.1625), (LOCAL*DIDI, 147.655...",478.554750,487.554750,4
25,25,D LOCAL*DIDI RIDES CIUDAD DE MEX MX DMM 171208...,"[(D, 138.6645, 145.1625), (LOCAL*DIDI, 147.655...",494.832750,503.832750,4
26,26,"CARGOS, ABONOS Y COMPRAS REGULARES (NO A MESES)","[(CARGOS,, 173.48925, 215.45624999999998), (AB...",521.004000,530.004000,4
27,27,Tarjeta adicional XXXX XXXX XXXX 5879,"[(Tarjeta, 217.30349999999999, 246.13049999999...",531.139500,540.139500,4
28,28,Fecha de Fecha de,"[(Fecha, 36.816, 59.0406945), (de, 61.25676375...",544.572803,552.573053,4
29,29,Monto,"[(Monto, 542.154, 564.3786944999999)]",547.577303,555.577553,4
30,30,Descripción del movimiento,"[(Descripción, 279.63525, 321.42055575), (del,...",549.077303,557.077553,4
31,31,la operación cargo,"[(la, 31.701, 37.925194499999996), (operación,...",553.581802,561.582052,4
32,32,SHEIN.COM SINGAPORE 11-SEP-2024 12-SEP-2024 +$...,"[(SHEIN.COM, 138.6645, 189.62249999999997), (S...",567.360000,576.360000,4
33,33,09/11/24 85.8515 USD RT 19.9381,"[(09/11/24, 138.6645, 173.0085), (85.8515, 175...",580.097250,589.097250,4

In [15]:
from table_reconstructor import TransactionTableReconstructor

table_reconstructor = TransactionTableReconstructor(grouped_rows, column_delimitation, statement_properties)

table_reconstructor.get_structured_table()

,Fecha de la operación,Fecha de cargo,Descripción del movimiento,Monto
0,,,(NO A MESES),A MESES)
1,,,Tarjeta titular XXXX XXXX XXXX 4540,
2,Fecha de,Fecha de,,
3,,,,Monto
4,,,Descripción del movimiento,
5,la operación,cargo,,
6,10-SEP-2024,11-SEP-2024,D LOCAL*DIDIFOOD CIUDAD DE MEX MX DMM 171208LT4,+$426.24
7,12-SEP-2024,04-OCT-2024,AMAZON MX A MESES M CIUDAD DE M 02/03,"+$1,390.85"
8,13-SEP-2024,17-SEP-2024,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4,+$56.00
9,17-SEP-2024,18-SEP-2024,SIMILARES F3 OTE MERIDA YUC MX CCA 010830V77,+$169.00
10,21-SEP-2024,23-SEP-2024,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4,+$84.00
11,21-SEP-2024,23-SEP-2024,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4,+$6.00
12,21-SEP-2024,23-SEP-2024,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4,+$23.25
13,21-SEP-2024,23-SEP-2024,"PAGO BANCA DIGITAL / SUCURSAL, GRACIAS.","-$5,630.57"
14,24-SEP-2024,25-SEP-2024,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4,+$95.00
15,25-SEP-2024,26-SEP-2024,APPLE.COM/BILL 866-712-77,+$49.25
16,,,09/25/24 2.5017 USD RT 19.6866,
17,25-SEP-2024,25-SEP-2024,DLOCAL*DIDI FOODS MIGUEL HIDALG MX DME 180122DU4,-$65.00
18,25-SEP-2024,25-SEP-2024,DLOCAL*DIDI FOODS MIGUEL HIDALG MX DME 180122DU4,+$65.00
19,27-SEP-2024,30-SEP-2024,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4,+$113.00
20,30-SEP-2024,30-SEP-2024,COMISION ADMINISTRACION TARJETA TITULAR,+$675.00
21,30-SEP-2024,30-SEP-2024,16.00 % IVA SOBRE COMISIONES E INTERESES,+$108.00
22,30-SEP-2024,02-OCT-2024,AMAZON MX MARKETPLACE CIUDAD DE MEX MX ANE 140...,+$92.00
23,02-OCT-2024,03-OCT-2024,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4,+$61.00
24,02-OCT-2024,03-OCT-2024,D LOCAL*DIDI RIDES CIUDAD DE MEX MX DMM 171208LT4,+$208.00
25,02-OCT-2024,03-OCT-2024,D LOCAL*DIDI RIDES CIUDAD DE MEX MX DMM 171208LT4,-$208.00
26,,,"CARGOS, ABONOS Y COMPRAS REGULARES (NO A MESES)",A MESES)
27,,,Tarjeta adicional XXXX XXXX XXXX 5879,
28,Fecha de,Fecha de,,
29,,,,Monto
30,,,Descripción del movimiento,
31,la operación,cargo,,
32,11-SEP-2024,12-SEP-2024,SHEIN.COM SINGAPORE,"+$1,711.72"
33,,,09/11/24 85.8515 USD RT 19.9381,

In [16]:
df_structured = table_reconstructor.reconstruct_table()
df_structured

,Fecha de la operación,Fecha de cargo,Descripción del movimiento,Monto
0,10-SEP-2024,11-SEP-2024,D LOCAL*DIDIFOOD CIUDAD DE MEX MX DMM 171208LT4,+$426.24
1,12-SEP-2024,04-OCT-2024,AMAZON MX A MESES M CIUDAD DE M 02/03,"+$1,390.85"
2,13-SEP-2024,17-SEP-2024,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4,+$56.00
3,17-SEP-2024,18-SEP-2024,SIMILARES F3 OTE MERIDA YUC MX CCA 010830V77,+$169.00
4,21-SEP-2024,23-SEP-2024,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4,+$84.00
5,21-SEP-2024,23-SEP-2024,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4,+$6.00
6,21-SEP-2024,23-SEP-2024,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4,+$23.25
7,21-SEP-2024,23-SEP-2024,"PAGO BANCA DIGITAL / SUCURSAL, GRACIAS.","-$5,630.57"
8,24-SEP-2024,25-SEP-2024,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4,+$95.00
9,25-SEP-2024,26-SEP-2024,APPLE.COM/BILL 866-712-77,+$49.25
10,25-SEP-2024,25-SEP-2024,DLOCAL*DIDI FOODS MIGUEL HIDALG MX DME 180122DU4,-$65.00
11,25-SEP-2024,25-SEP-2024,DLOCAL*DIDI FOODS MIGUEL HIDALG MX DME 180122DU4,+$65.00
12,27-SEP-2024,30-SEP-2024,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4,+$113.00
13,30-SEP-2024,30-SEP-2024,COMISION ADMINISTRACION TARJETA TITULAR,+$675.00
14,30-SEP-2024,30-SEP-2024,16.00 % IVA SOBRE COMISIONES E INTERESES,+$108.00
15,30-SEP-2024,02-OCT-2024,AMAZON MX MARKETPLACE CIUDAD DE MEX MX ANE 140...,+$92.00
16,02-OCT-2024,03-OCT-2024,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4,+$61.00
17,02-OCT-2024,03-OCT-2024,D LOCAL*DIDI RIDES CIUDAD DE MEX MX DMM 171208LT4,+$208.00
18,02-OCT-2024,03-OCT-2024,D LOCAL*DIDI RIDES CIUDAD DE MEX MX DMM 171208LT4,-$208.00
19,11-SEP-2024,12-SEP-2024,SHEIN.COM SINGAPORE,"+$1,711.72"

In [17]:
from table_normalizer import TransactionTableNormalizer

normalizer = TransactionTableNormalizer(df_structured, extracted_words, statement_properties)

df_normalized = normalizer.normalize_table()
df_normalized

,Date,Description,Amount,Type
0,2024-09-10,D LOCAL*DIDIFOOD CIUDAD DE MEX MX DMM 171208LT4,-426.24,Cargo
1,2024-09-12,AMAZON MX A MESES M CIUDAD DE M 02/03,-1390.85,Cargo
2,2024-09-13,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4,-56.00,Cargo
3,2024-09-17,SIMILARES F3 OTE MERIDA YUC MX CCA 010830V77,-169.00,Cargo
4,2024-09-21,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4,-84.00,Cargo
5,2024-09-21,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4,-6.00,Cargo
6,2024-09-21,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4,-23.25,Cargo
7,2024-09-21,"PAGO BANCA DIGITAL / SUCURSAL, GRACIAS.",5630.57,Abono
8,2024-09-24,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4,-95.00,Cargo
9,2024-09-25,APPLE.COM/BILL 866-712-77,-49.25,Cargo
10,2024-09-25,DLOCAL*DIDI FOODS MIGUEL HIDALG MX DME 180122DU4,65.00,Abono
11,2024-09-25,DLOCAL*DIDI FOODS MIGUEL HIDALG MX DME 180122DU4,-65.00,Cargo
12,2024-09-27,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4,-113.00,Cargo
13,2024-09-30,COMISION ADMINISTRACION TARJETA TITULAR,-675.00,Cargo
14,2024-09-30,16.00 % IVA SOBRE COMISIONES E INTERESES,-108.00,Cargo
15,2024-09-30,AMAZON MX MARKETPLACE CIUDAD DE MEX MX ANE 140...,-92.00,Cargo
16,2024-10-02,DLOCAL*DIDI RIDES CUAUHTEMOC MX DMM 171208LT4,-61.00,Cargo
17,2024-10-02,D LOCAL*DIDI RIDES CIUDAD DE MEX MX DMM 171208LT4,-208.00,Cargo
18,2024-10-02,D LOCAL*DIDI RIDES CIUDAD DE MEX MX DMM 171208LT4,208.00,Abono
19,2024-09-11,SHEIN.COM SINGAPORE,-1711.72,Cargo

In [18]:
from data_exporter import CsvExporter
from config import OUTPUTS_FOLDER

exporter = CsvExporter(df_normalized)
file_path = os.path.join(OUTPUTS_FOLDER, bank, f'{bank}_{statement_type}.csv')

exporter.export_to_csv(file_path)

Data exported to c:\Proyectos\Aether\Aether_v1\documents\outputs\banorte\banorte_credit.csv successfully.