In [28]:
import sys
import os

current_file_path = os.path.abspath(os.getcwd()) # Funciona solo para JupyterNotebooks
# Obtener la ruta del directorio raíz del proyecto
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(current_file_path)))
# Añadir el directorio raíz del proyecto al sys.path
sys.path.append(PROJECT_ROOT)

INPUTS_FOLDER = os.path.join(PROJECT_ROOT, 'tests', 'test_data', 'inputs')
OUTPUTS_FOLDER = os.path.join(PROJECT_ROOT, 'tests', 'test_data', 'outputs')

def get_file_from_path(file_path: str) -> str:
    return os.path.join(INPUTS_FOLDER, file_path)

test_files = [
    'banorte_credit_new.pdf',
    'banorte_credit_old.pdf',
    'banorte_debit.pdf',
    'bbva_debit.pdf',
]

file_path = get_file_from_path('bbva_debit.pdf')

In [29]:
from models import DocumentProcessingFacade
import logging
logging.getLogger('pdfminer').setLevel(logging.ERROR) # Abvoid PDFMiner warnings

doc_processor = DocumentProcessingFacade(file_path)
statement_properties = doc_processor.get_statement_properties()
bank = statement_properties['bank']
statement_type = statement_properties['statement_type']
new_format = statement_properties['new_format']

print(bank, ' - ', statement_type, ' - ', new_format)

bbva  -  debit  -  None

In [30]:
corrected_extracted_words = doc_processor.get_corrected_extracted_words()
corrected_extracted_words

      page      text          x0         top          x1      bottom
0        1    Estado  510.546000    1.219000  544.314000   13.219000
1        1        de  546.858000    1.219000  559.638000   13.219000
2        1    Cuenta  562.182000    1.219000  598.182000   13.219000
3        1  Libretón  459.986607   16.654410  498.904607   27.654410
4        1    Básico  501.236607   16.654410  530.397608   27.654410
...    ...       ...         ...         ...         ...         ...
2006     8        de  500.295960  773.127129  508.503960  782.127129
2007     8        la  510.555960  773.127129  516.297960  782.127129
2008     8       Ley  518.349960  773.127129  530.247960  782.127129
2009     8  Personas  532.299960  773.127129  563.475960  782.127129
2010     8   Morales  565.527960  773.127129  591.771960  782.127129

[2011 rows x 6 columns]

In [31]:
if statement_type == 'debit':
    corrected_words_path = os.path.join(INPUTS_FOLDER, f'{bank}_{statement_type}_corrected_words.csv')
elif statement_type == 'credit':
    _format = 'new' if new_format else 'old'
    corrected_words_path = os.path.join(INPUTS_FOLDER, f'{bank}_{statement_type}_{_format}_corrected_words.csv')
    
corrected_extracted_words.to_csv(corrected_words_path, index=False)

In [32]:
from models import TableProcessingFacade

table_processor = TableProcessingFacade(corrected_extracted_words, statement_properties)
reconstructor = table_processor.get_reconstructor()
structured_table = reconstructor.get_structured_table()
structured_table

,Date,Description,CARGOS,ABONOS,OPERACION,LIQUIDACION
0,None,FECHA SALDO,,,,
1,None,OPER LIQ DESCRIPCION REFERENCIA CARGOS ABONOS ...,,,,
2,15/MAY,PAGO CUENTA DE TERCERO,40.00,,,
3,None,Referencia 1634723960 BNET 1592044105 PAGO PRE...,,,,
4,15/MAY,SPEI ENVIADO SANTANDER,25.00,,,
...,...,...,...,...,...,...
149,None,CETES DIRECTO,,,,
150,None,Total de Movimientos,,,,
151,None,TOTAL IMPORTE CARGOS TOTAL MOVIMIENTOS CARGOS 30,,,,
152,None,TOTAL IMPORTE ABONOS TOTAL MOVIMIENTOS ABONOS 6,,,,
153,None,Le informamos que puede,,,,

In [33]:
reconstructed_table = table_processor.reconstruct_table()
reconstructed_table

,Date,Description,CARGOS,ABONOS,OPERACION,LIQUIDACION
0,15/MAY,PAGO CUENTA DE TERCERO Referencia 1634723960 ...,40.00,,,
1,15/MAY,SPEI ENVIADO SANTANDER Referencia 0059269420 ...,25.00,,,
2,15/MAY,PAGO CUENTA DE TERCERO Referencia 1641104987 ...,60.00,,"266,326.99","266,451.99"
3,17/MAY,SPEI ENVIADO SANTANDER Referencia 0063053690 ...,850.00,,"265,476.99","265,476.99"
4,18/MAY,SPEI ENVIADO STP Referencia 0064298989 646 18...,"80,000.00",,,
5,18/MAY,SPEI ENVIADO STP Referencia 0064318415 646 18...,500.00,,,
6,18/MAY,SAT Referencia GUIA:0095194 REF:042229R345003...,"13,621.00",,,
7,18/MAY,SAT Referencia GUIA:0112519 REF:042229QU05003...,"7,398.00",,,
8,18/MAY,SAT Referencia GUIA:0132561 REF:042229QD92003...,"3,832.00",,,
9,18/MAY,SAT Referencia GUIA:0146586 REF:042229Q995003...,"4,971.00",,,
10,18/MAY,SPEI ENVIADO STP Referencia 0064426108 646 18...,"20,000.00",,,
11,18/MAY,SPEI ENVIADO STP Referencia 0064455171 646 18...,"1,000.00",,,
12,18/MAY,SPEI ENVIADO STP Referencia 0064460879 646 18...,"5,000.00",,"129,154.99","129,105.99"
13,19/MAY,SPEI ENVIADO SANTANDER Referencia 0066358089 ...,150.00,,,
14,19/MAY,PAYPAL ITUNESAPPST APPL Referencia ******1422...,49.00,,"128,955.99","128,955.99"
15,20/MAY,SPEI ENVIADO JP MORGAN Referencia 0067717291 ...,"80,000.00",,,
16,20/MAY,SPEI ENVIADO SANTANDER Referencia 0069155835 ...,250.00,,"48,705.99","48,955.99"
17,22/MAY,PAGO CUENTA DE TERCERO Referencia 2234871906 ...,400.00,,"48,305.99","48,955.99"
18,25/MAY,PAGO CUENTA DE TERCERO Referencia 2466371210 ...,"1,160.00",,,
19,25/MAY,SPEI RECIBIDOSTP Referencia 0172116059 646 22...,,"29,030.63","76,176.62","76,176.62"
20,29/MAY,PAGO CUENTA DE TERCERO Referencia 2805194160 ...,,375.00,,
21,29/MAY,PAGO CUENTA DE TERCERO Referencia 2827369555 ...,,250.00,,
22,29/MAY,PAGO CUENTA DE TERCERO Referencia 2828380208 ...,,96.00,"76,897.62","76,176.62"
23,01/JUN,SPEI ENVIADO STP Referencia 0089224219 646 01...,"2,500.00",,"74,397.62","74,397.62"
24,02/JUN,SPEI ENVIADO JP MORGAN Referencia 0092044540 ...,"2,000.00",,"72,397.62","72,182.62"
25,03/JUN,SPEI RECIBIDOJP MORGAN Referencia 0192783026 ...,,"64,708.47",,
26,03/JUN,SPEI ENVIADO JP MORGAN Referencia 0094143811 ...,"15,000.00",,,
27,03/JUN,POINTMP*ALBRIZZO Referencia ******1422 RFC: M...,215.00,,"121,891.09","121,891.09"
28,06/JUN,PAGO TARJETA DE CREDITO Referencia 3498188369...,"20,729.43",,,
29,06/JUN,PAYPAL ITUNESAPPST APPL Referencia ******1422...,149.00,,"101,012.66","101,012.66"
30,08/JUN,CFE SUM SERV BAS MU Referencia ******3870 RFC...,652.00,,"100,360.66","100,360.66"
31,10/JUN,SPEI RECIBIDOBANORTE Referencia 0107643376 07...,,"25,914.23",,
32,10/JUN,PAYPAL GOOGLE YOUTUBE S Referencia ******1422...,239.00,,,
33,10/JUN,NETFLIX COM 1 Referencia ******3870 RFC: NME ...,299.00,,"125,736.89","125,736.89"
34,12/JUN,SPEI ENVIADO STP Referencia 0059152879 646 12...,"7,583.00",,"118,153.89","125,736.89"
35,13/JUN,SPEI ENVIADO NAFIN Referencia 0060313649 135 ...,"50,000.00",,"68,153.89","68,153.89"

In [34]:
if statement_type == 'debit':
    reconstructed_table_path = os.path.join(INPUTS_FOLDER, f'{bank}_{statement_type}_reconstructed_table.csv')
elif statement_type == 'credit':
    _format = 'new' if new_format else 'old'
    reconstructed_table_path = os.path.join(INPUTS_FOLDER, f'{bank}_{statement_type}_{_format}_reconstructed_table.csv')
    
reconstructed_table.to_csv(reconstructed_table_path, index=False)

In [35]:
from models import DataProcessingFacade

data_processor = DataProcessingFacade(corrected_extracted_words, reconstructed_table, statement_properties)
df_transactions = data_processor.get_normalized_table()
df_transactions

,Date,Description,Amount,Type
0,2022-05-15,PAGO CUENTA DE TERCERO Referencia 1634723960 ...,-40.00,Cargo
2,2022-05-15,PAGO CUENTA DE TERCERO Referencia 1641104987 ...,-60.00,Cargo
36,2022-05-15,Saldo Inicial,266451.99,Saldo Inicial
1,2022-05-15,SPEI ENVIADO SANTANDER Referencia 0059269420 ...,-25.00,Cargo
3,2022-05-17,SPEI ENVIADO SANTANDER Referencia 0063053690 ...,-850.00,Cargo
4,2022-05-18,SPEI ENVIADO STP Referencia 0064298989 646 18...,-80000.00,Cargo
5,2022-05-18,SPEI ENVIADO STP Referencia 0064318415 646 18...,-500.00,Cargo
6,2022-05-18,SAT Referencia GUIA:0095194 REF:042229R345003...,-13621.00,Cargo
7,2022-05-18,SAT Referencia GUIA:0112519 REF:042229QU05003...,-7398.00,Cargo
8,2022-05-18,SAT Referencia GUIA:0132561 REF:042229QD92003...,-3832.00,Cargo
9,2022-05-18,SAT Referencia GUIA:0146586 REF:042229Q995003...,-4971.00,Cargo
10,2022-05-18,SPEI ENVIADO STP Referencia 0064426108 646 18...,-20000.00,Cargo
11,2022-05-18,SPEI ENVIADO STP Referencia 0064455171 646 18...,-1000.00,Cargo
12,2022-05-18,SPEI ENVIADO STP Referencia 0064460879 646 18...,-5000.00,Cargo
13,2022-05-19,SPEI ENVIADO SANTANDER Referencia 0066358089 ...,-150.00,Cargo
14,2022-05-19,PAYPAL ITUNESAPPST APPL Referencia ******1422...,-49.00,Cargo
15,2022-05-20,SPEI ENVIADO JP MORGAN Referencia 0067717291 ...,-80000.00,Cargo
16,2022-05-20,SPEI ENVIADO SANTANDER Referencia 0069155835 ...,-250.00,Cargo
17,2022-05-22,PAGO CUENTA DE TERCERO Referencia 2234871906 ...,-400.00,Cargo
19,2022-05-25,SPEI RECIBIDOSTP Referencia 0172116059 646 22...,29030.63,Abono
18,2022-05-25,PAGO CUENTA DE TERCERO Referencia 2466371210 ...,-1160.00,Cargo
22,2022-05-29,PAGO CUENTA DE TERCERO Referencia 2828380208 ...,96.00,Abono
20,2022-05-29,PAGO CUENTA DE TERCERO Referencia 2805194160 ...,375.00,Abono
21,2022-05-29,PAGO CUENTA DE TERCERO Referencia 2827369555 ...,250.00,Abono
23,2022-06-01,SPEI ENVIADO STP Referencia 0089224219 646 01...,-2500.00,Cargo
24,2022-06-02,SPEI ENVIADO JP MORGAN Referencia 0092044540 ...,-2000.00,Cargo
25,2022-06-03,SPEI RECIBIDOJP MORGAN Referencia 0192783026 ...,64708.47,Abono
26,2022-06-03,SPEI ENVIADO JP MORGAN Referencia 0094143811 ...,-15000.00,Cargo
27,2022-06-03,POINTMP*ALBRIZZO Referencia ******1422 RFC: M...,-215.00,Cargo
29,2022-06-06,PAYPAL ITUNESAPPST APPL Referencia ******1422...,-149.00,Cargo
28,2022-06-06,PAGO TARJETA DE CREDITO Referencia 3498188369...,-20729.43,Cargo
30,2022-06-08,CFE SUM SERV BAS MU Referencia ******3870 RFC...,-652.00,Cargo
31,2022-06-10,SPEI RECIBIDOBANORTE Referencia 0107643376 07...,25914.23,Abono
32,2022-06-10,PAYPAL GOOGLE YOUTUBE S Referencia ******1422...,-239.00,Cargo
33,2022-06-10,NETFLIX COM 1 Referencia ******3870 RFC: NME ...,-299.00,Cargo
34,2022-06-12,SPEI ENVIADO STP Referencia 0059152879 646 12...,-7583.00,Cargo
35,2022-06-13,SPEI ENVIADO NAFIN Referencia 0060313649 135 ...,-50000.00,Cargo

In [36]:
from models import CsvExporter

exporter = CsvExporter(df_transactions)
if statement_type == 'debit':
    normalized_table_path = os.path.join(OUTPUTS_FOLDER, f'{bank}_{statement_type}_normalized_table.csv')
elif statement_type == 'credit':
    _format = 'new' if new_format else 'old'
    normalized_table_path = os.path.join(OUTPUTS_FOLDER, f'{bank}_{statement_type}_{_format}_normalized_table.csv')

exporter.export_data(normalized_table_path)